GET http://localhost:3000/shows


###

GET http://localhost:3000/shows/1

###

POST http://localhost:3000/shows
Content-Type: application/json

{
  "name": "The Simpsons",
  "episodes": 999
}

####
PATCH http://localhost:3000/shows/1
Content-Type: application/json

{
  "name": "The Spongebob"
}